parameters:

    wxr_news.post.class: Application\WXR\NewsBundle\Entity\Post
    wxr_news.category.class: Application\WXR\NewsBundle\Entity\Category
    wxr_news.tag.class: Application\WXR\NewsBundle\Entity\Tag

services:

    wxr_news.post.manager.default:
        class: WXR\NewsBundle\Entity\PostManager
        arguments: [@doctrine.orm.entity_manager, %wxr_news.post.class%]

    wxr_news.post.admin:
        class: %wxr_news.post.admin.class%
        arguments: [ ~, %wxr_news.post.class%, %wxr_news.post.admin.controller% ]
        calls:
            - [ setTranslationDomain, [ %wxr_news.translation_domain% ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_news
                label: posts
                label_catalogue: %wxr_news.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore

    wxr_news.category.manager.default:
        class: WXR\NewsBundle\Entity\CategoryManager
        arguments: [@doctrine.orm.entity_manager, %wxr_news.category.class%, %wxr_news.post.class%]

    wxr_news.category.admin:
        class: %wxr_news.category.admin.class%
        arguments: [ ~, %wxr_news.category.class%, %wxr_news.category.admin.controller% ]
        calls:
            - [ setTranslationDomain, [ %wxr_news.translation_domain% ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_news
                label: categories
                label_catalogue: %wxr_news.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore

    wxr_news.tag.manager.default:
        class: WXR\NewsBundle\Entity\TagManager
        arguments: [@doctrine.orm.entity_manager, %wxr_news.tag.class%]

    wxr_news.tag.admin:
        class: %wxr_news.tag.admin.class%
        arguments: [ ~, %wxr_news.tag.class%, %wxr_news.tag.admin.controller% ]
        calls:
            - [ setTranslationDomain, [ %wxr_news.translation_domain% ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_news
                label: tags
                label_catalogue: %wxr_news.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore
